import { createSlice } from "@reduxjs/toolkit";
import {
  img1,
  img2,
  img3,
  img4,
  img5,
  img6,
  img7,
  img8,
  img9,
  img10,
  img11,
  img12,
  img13,
  img14,
  img15,
  img16,
  img17,
  img18,
  img19,
  img20,
  img21,
  img22,
  img23,
  img24,
  img25,
  img26,
  img27,
  img28,
  img29,
  img30,
  img31,
  img32,
  img33,
  img34,
  img35,
  img36,
  img37,
  img38,
  img39,
  img40,
  img41,
  img42,
  img43,
  img44,
  img45,
  img46,
  img47,
  img48,
} from "./IndexImages";

const initialState = {
  allProducts: [
    {
      id: "1",
      name: "Nike Pegasus 40",
      img: img1,
      desc: "A springy ride for any run, the Pegs familiar, just-for-you feel returns to help you accomplish your goals. This version has the same responsiveness and neutral support you love, but with improved comfort in those sensitive areas of your foot, like the arch and toes.",
      price: 110,
      category: "shoes",
      gender: "men",
      trending: true,
    },
    {
      id: "2",
      name: "LeBron 20",
      img: img2,
      desc: "A springy ride for any run, the Pegs familiar, just-for-you feel returns to help you accomplish your goals. This version has the same responsiveness and neutral support you love, but with improved comfort in those sensitive areas of your foot, like the arch and toes.",
      price: 100.99,
      category: "shoes",
      gender: "men",
      trending: false,
    },
    {
      id: "3",
      name: "Nike Air Force 1 '07",
      img: img3,
      desc: "A springy ride for any run, the Pegs familiar, just-for-you feel returns to help you accomplish your goals. This version has the same responsiveness and neutral support you love, but with improved comfort in those sensitive areas of your foot, like the arch and toes.",
      price: 150,
      category: "shoes",
      gender: "men",
      trending: false,
    },
    {
      id: "4",
      name: "Jordan Retro 6 G NRG",
      img: img4,
      desc: "A springy ride for any run, the Pegs familiar, just-for-you feel returns to help you accomplish your goals. This version has the same responsiveness and neutral support you love, but with improved comfort in those sensitive areas of your foot, like the arch and toes.",
      price: 130,
      category: "shoes",
      gender: "men",
      trending: false,
    },
    {
      id: "5",
      name: "Nike React Infinity Run Flyknit 3",
      img: img5,
      desc: "A springy ride for any run, the Pegs familiar, just-for-you feel returns to help you accomplish your goals. This version has the same responsiveness and neutral support you love, but with improved comfort in those sensitive areas of your foot, like the arch and toes.",
      price: 110,
      category: "shoes",
      gender: "men",
      trending: false,
    },
    {
      id: "6",
      name: "Nike Metcon 8",
      img: img6,
      desc: "A springy ride for any run, the Pegs familiar, just-for-you feel returns to help you accomplish your goals. This version has the same responsiveness and neutral support you love, but with improved comfort in those sensitive areas of your foot, like the arch and toes.",
      price: 144,
      category: "shoes",
      gender: "men",
      trending: false,
    },
    {
      id: "7",
      name: "Nike Air Max Terrascape Plus",
      img: img7,
      desc: "A springy ride for any run, the Pegs familiar, just-for-you feel returns to help you accomplish your goals. This version has the same responsiveness and neutral support you love, but with improved comfort in those sensitive areas of your foot, like the arch and toes.",
      price: 120,
      category: "shoes",
      gender: "men",
      trending: false,
    },
    {
      id: "8",
      name: "Nike Air Max Terrascape 90",
      img: img8,
      desc: "A springy ride for any run, the Pegs familiar, just-for-you feel returns to help you accomplish your goals. This version has the same responsiveness and neutral support you love, but with improved comfort in those sensitive areas of your foot, like the arch and toes.",
      price: 166,
      category: "shoes",
      gender: "men",
      trending: true,
    },
    {
      id: "9",
      name: "Nike Air Max 1 '86 OG G",
      img: img9,
      desc: "A springy ride for any run, the Pegs familiar, just-for-you feel returns to help you accomplish your goals. This version has the same responsiveness and neutral support you love, but with improved comfort in those sensitive areas of your foot, like the arch and toes.",
      price: 100,
      category: "shoes",
      gender: "men",
      trending: false,
    },
    {
      id: "10",
      name: "Nike Sportswear Club Fleece",
      img: img10,
      desc: "A closet staple, the Nike Sportswear Club Fleece Joggers combine a classic look with the soft comfort of fleece for an elevated, everyday look that you can wear every day.",
      price: 50,
      category: "clothing",
      gender: "men",
      trending: true,
    },
    {
      id: "11",
      name: "Jordan Brooklyn Fleece",
      img: img11,
      desc: "A closet staple, the Nike Sportswear Club Fleece Joggers combine a classic look with the soft comfort of fleece for an elevated, everyday look that you can wear every day.",
      price: 40,
      category: "clothing",
      gender: "men",
      trending: false,
    },
    {
      id: "12",
      name: "Jordan AJ11",
      img: img12,
      desc: "A closet staple, the Nike Sportswear Club Fleece Joggers combine a classic look with the soft comfort of fleece for an elevated, everyday look that you can wear every day.",
      price: 20,
      category: "clothing",
      gender: "men",
      trending: false,
    },
    {
      id: "13",
      name: "Nike Therma",
      img: img13,
      desc: "A closet staple, the Nike Sportswear Club Fleece Joggers combine a classic look with the soft comfort of fleece for an elevated, everyday look that you can wear every day.",
      price: 58,
      category: "clothing",
      gender: "men",
      trending: false,
    },
    {
      id: "14",
      name: "Nike Pro Dri-FIT",
      img: img14,
      desc: "A closet staple, the Nike Sportswear Club Fleece Joggers combine a classic look with the soft comfort of fleece for an elevated, everyday look that you can wear every day.",
      price: 33,
      category: "clothing",
      gender: "men",
      trending: false,
    },
    {
      id: "15",
      name: "Nike Sportswear Club Fleece",
      img: img15,
      desc: "A closet staple, the Nike Sportswear Club Fleece Joggers combine a classic look with the soft comfort of fleece for an elevated, everyday look that you can wear every day.",
      price: 42,
      category: "clothing",
      gender: "men",
      trending: false,
    },
    {
      id: "16",
      name: "Nike Sportswear Club Fleece",
      img: img16,
      desc: "A closet staple, the Nike Sportswear Club Fleece Joggers combine a classic look with the soft comfort of fleece for an elevated, everyday look that you can wear every day.",
      price: 60,
      category: "clothing",
      gender: "men",
      trending: false,
    },
    {
      id: "17",
      name: "Jordan Sport DNA '85",
      img: img17,
      desc: "A closet staple, the Nike Sportswear Club Fleece Joggers combine a classic look with the soft comfort of fleece for an elevated, everyday look that you can wear every day.",
      price: 42,
      category: "clothing",
      gender: "men",
      trending: false,
    },
    {
      id: "18",
      name: "Nike Ready",
      img: img18,
      desc: "A closet staple, the Nike Sportswear Club Fleece Joggers combine a classic look with the soft comfort of fleece for an elevated, everyday look that you can wear every day.",
      price: 50,
      category: "clothing",
      gender: "men",
      trending: false,
    },
    {
      id: "19",
      name: "Nike Gamma Force",
      img: img19,
      desc: "Layers upon layers of dimensional style—that's a force to be reckoned with. Offering both comfort and versatility, these kicks are rooted in heritage basketball culture. Collar materials pay homage to vintage sport while the subtle platform elevates your look, literally.",
      price: 120,
      category: "shoes",
      gender: "women",
      trending: true,
    },
    {
      id: "20",
      name: "Nike Free Metcon 5",
      img: img20,
      desc: "Layers upon layers of dimensional style—that's a force to be reckoned with. Offering both comfort and versatility, these kicks are rooted in heritage basketball culture. Collar materials pay homage to vintage sport while the subtle platform elevates your look, literally.",
      price: 110,
      category: "shoes",
      gender: "women",
      trending: false,
    },
    {
      id: "21",
      name: "Nike SuperRep Go 3 Flyknit Next Nature",
      img: img21,
      desc: "Layers upon layers of dimensional style—that's a force to be reckoned with. Offering both comfort and versatility, these kicks are rooted in heritage basketball culture. Collar materials pay homage to vintage sport while the subtle platform elevates your look, literally.",
      price: 100,
      category: "shoes",
      gender: "women",
      trending: true,
    },
    {
      id: "22",
      name: "Nike Pegasus 40",
      img: img22,
      desc: "Layers upon layers of dimensional style—that's a force to be reckoned with. Offering both comfort and versatility, these kicks are rooted in heritage basketball culture. Collar materials pay homage to vintage sport while the subtle platform elevates your look, literally.",
      price: 130,
      category: "shoes",
      gender: "women",
      trending: true,
    },
    {
      id: "23",
      name: "Nike Air Max 1 '87",
      img: img23,
      desc: "Layers upon layers of dimensional style—that's a force to be reckoned with. Offering both comfort and versatility, these kicks are rooted in heritage basketball culture. Collar materials pay homage to vintage sport while the subtle platform elevates your look, literally.",
      price: 160,
      category: "shoes",
      gender: "women",
      trending: true,
    },
    {
      id: "24",
      name: "Nike Court Legacy Lift",
      img: img24,
      desc: "Layers upon layers of dimensional style—that's a force to be reckoned with. Offering both comfort and versatility, these kicks are rooted in heritage basketball culture. Collar materials pay homage to vintage sport while the subtle platform elevates your look, literally.",
      price: 120,
      category: "shoes",
      gender: "women",
      trending: true,
    },
    {
      id: "25",
      name: "Nike Air VaporMax 2023 Flyknit",
      img: img25,
      desc: "Layers upon layers of dimensional style—that's a force to be reckoned with. Offering both comfort and versatility, these kicks are rooted in heritage basketball culture. Collar materials pay homage to vintage sport while the subtle platform elevates your look, literally.",
      price: 170,
      category: "shoes",
      gender: "women",
      trending: false,
    },
    {
      id: "26",
      name: "Nike Air Max 97",
      img: img26,
      desc: "Layers upon layers of dimensional style—that's a force to be reckoned with. Offering both comfort and versatility, these kicks are rooted in heritage basketball culture. Collar materials pay homage to vintage sport while the subtle platform elevates your look, literally.",
      price: 155,
      category: "shoes",
      gender: "women",
      trending: false,
    },
    {
      id: "27",
      name: "Nike Blazer Low Platform",
      img: img27,
      desc: "Layers upon layers of dimensional style—that's a force to be reckoned with. Offering both comfort and versatility, these kicks are rooted in heritage basketball culture. Collar materials pay homage to vintage sport while the subtle platform elevates your look, literally.",
      price: 125,
      category: "shoes",
      gender: "women",
      trending: false,
    },
    {
      id: "28",
      name: "Nike Sportswear Phoenix Fleece",
      img: img28,
      desc: "Rise up and transform your fleece wardrobe with strong cozy vibes. These oversized Phoenix Fleece sweats have extra room in the legs for a fit that's comfy and relaxed. The taller ribbed waistline sits higher on your hips for a stay-put, snug feel and a bold look.",
      price: 55,
      category: "clothing",
      gender: "women",
      trending: false,
    },
    {
      id: "29",
      name: "Nike Sportswear Essential",
      img: img29,
      desc: "Rise up and transform your fleece wardrobe with strong cozy vibes. These oversized Phoenix Fleece sweats have extra room in the legs for a fit that's comfy and relaxed. The taller ribbed waistline sits higher on your hips for a stay-put, snug feel and a bold look.",
      price: 70,
      category: "clothing",
      gender: "women",
      trending: false,
    },
    {
      id: "30",
      name: "Nike Sportswear Collection",
      img: img30,
      desc: "Rise up and transform your fleece wardrobe with strong cozy vibes. These oversized Phoenix Fleece sweats have extra room in the legs for a fit that's comfy and relaxed. The taller ribbed waistline sits higher on your hips for a stay-put, snug feel and a bold look.",
      price: 23,
      category: "clothing",
      gender: "women",
      trending: false,
    },
    {
      id: "31",
      name: "Nike Dri-FIT",
      img: img31,
      desc: "Rise up and transform your fleece wardrobe with strong cozy vibes. These oversized Phoenix Fleece sweats have extra room in the legs for a fit that's comfy and relaxed. The taller ribbed waistline sits higher on your hips for a stay-put, snug feel and a bold look.",
      price: 35,
      category: "clothing",
      gender: "women",
      trending: false,
    },
    {
      id: "32",
      name: "Nike Sportswear Collection",
      img: img32,
      desc: "Rise up and transform your fleece wardrobe with strong cozy vibes. These oversized Phoenix Fleece sweats have extra room in the legs for a fit that's comfy and relaxed. The taller ribbed waistline sits higher on your hips for a stay-put, snug feel and a bold look.",
      price: 50,
      category: "clothing",
      gender: "women",
      trending: false,
    },
    {
      id: "33",
      name: "Nike Sportswear Collection",
      img: img33,
      desc: "Rise up and transform your fleece wardrobe with strong cozy vibes. These oversized Phoenix Fleece sweats have extra room in the legs for a fit that's comfy and relaxed. The taller ribbed waistline sits higher on your hips for a stay-put, snug feel and a bold look.",
      price: 30,
      category: "clothing",
      gender: "women",
      trending: false,
    },
    {
      id: "34",
      name: "Nike Sportswear Essential",
      img: img34,
      desc: "Rise up and transform your fleece wardrobe with strong cozy vibes. These oversized Phoenix Fleece sweats have extra room in the legs for a fit that's comfy and relaxed. The taller ribbed waistline sits higher on your hips for a stay-put, snug feel and a bold look.",
      price: 28,
      category: "clothing",
      gender: "women",
      trending: false,
    },
    {
      id: "35",
      name: "Nike Sportswear Essential",
      img: img35,
      desc: "Rise up and transform your fleece wardrobe with strong cozy vibes. These oversized Phoenix Fleece sweats have extra room in the legs for a fit that's comfy and relaxed. The taller ribbed waistline sits higher on your hips for a stay-put, snug feel and a bold look.",
      price: 42,
      category: "clothing",
      gender: "women",
      trending: false,
    },
    {
      id: "36",
      name: "Nike Sportswear Essential",
      img: img36,
      desc: "Rise up and transform your fleece wardrobe with strong cozy vibes. These oversized Phoenix Fleece sweats have extra room in the legs for a fit that's comfy and relaxed. The taller ribbed waistline sits higher on your hips for a stay-put, snug feel and a bold look.",
      price: 33,
      category: "clothing",
      gender: "women",
      trending: false,
    },
    {
      id: "37",
      name: "Nike Elemental Premium",
      img: img37,
      desc: "Sleek, modern and made from durable polyester, the Nike Elemental Backpack is a storage staple. Its large zippered compartment comfortably fits shoes or gym clothes along with your books and laptop for school. Two exterior pockets help keep your small essentials organized and accessible.",
      price: 40,
      category: "accessories",
      gender: "unisex",
      trending: false,
    },
    {
      id: "38",
      name: "Nike Club",
      img: img38,
      desc: "Sleek, modern and made from durable polyester, the Nike Elemental Backpack is a storage staple. Its large zippered compartment comfortably fits shoes or gym clothes along with your books and laptop for school. Two exterior pockets help keep your small essentials organized and accessible.",
      price: 22,
      category: "accessories",
      gender: "unisex",
      trending: false,
    },
    {
      id: "39",
      name: "Nike Club",
      img: img39,
      desc: "Sleek, modern and made from durable polyester, the Nike Elemental Backpack is a storage staple. Its large zippered compartment comfortably fits shoes or gym clothes along with your books and laptop for school. Two exterior pockets help keep your small essentials organized and accessible.",
      price: 25,
      category: "accessories",
      gender: "unisex",
      trending: true,
    },
    {
      id: "40",
      name: "Nike NV07",
      img: img40,
      desc: "Sleek, modern and made from durable polyester, the Nike Elemental Backpack is a storage staple. Its large zippered compartment comfortably fits shoes or gym clothes along with your books and laptop for school. Two exterior pockets help keep your small essentials organized and accessible.",
      price: 35,
      category: "accessories",
      gender: "unisex",
      trending: false,
    },
    {
      id: "41",
      name: "Nike Dri-FIT Club",
      img: img41,
      desc: "Sleek, modern and made from durable polyester, the Nike Elemental Backpack is a storage staple. Its large zippered compartment comfortably fits shoes or gym clothes along with your books and laptop for school. Two exterior pockets help keep your small essentials organized and accessible.",
      price: 26,
      category: "accessories",
      gender: "unisex",
      trending: false,
    },
    {
      id: "42",
      name: "Nike Elemental Premium",
      img: img42,
      desc: "Sleek, modern and made from durable polyester, the Nike Elemental Backpack is a storage staple. Its large zippered compartment comfortably fits shoes or gym clothes along with your books and laptop for school. Two exterior pockets help keep your small essentials organized and accessible.",
      price: 40,
      category: "accessories",
      gender: "unisex",
      trending: false,
    },
    {
      id: "43",
      name: "Nike Elemental Premium",
      img: img43,
      desc: "Sleek, modern and made from durable polyester, the Nike Elemental Backpack is a storage staple. Its large zippered compartment comfortably fits shoes or gym clothes along with your books and laptop for school. Two exterior pockets help keep your small essentials organized and accessible.",
      price: 45,
      category: "accessories",
      gender: "unisex",
      trending: true,
    },
    {
      id: "44",
      name: "Nike Hike",
      img: img44,
      desc: "Sleek, modern and made from durable polyester, the Nike Elemental Backpack is a storage staple. Its large zippered compartment comfortably fits shoes or gym clothes along with your books and laptop for school. Two exterior pockets help keep your small essentials organized and accessible.",
      price: 32,
      category: "accessories",
      gender: "unisex",
      trending: false,
    },
    {
      id: "45",
      name: "Nike Sportswear Essentials",
      img: img45,
      desc: "Sleek, modern and made from durable polyester, the Nike Elemental Backpack is a storage staple. Its large zippered compartment comfortably fits shoes or gym clothes along with your books and laptop for school. Two exterior pockets help keep your small essentials organized and accessible.",
      price: 56,
      category: "accessories",
      gender: "unisex",
      trending: false,
    },
    {
      id: "46",
      name: "Nike Sportswear Essentials",
      img: img46,
      desc: "Sleek, modern and made from durable polyester, the Nike Elemental Backpack is a storage staple. Its large zippered compartment comfortably fits shoes or gym clothes along with your books and laptop for school. Two exterior pockets help keep your small essentials organized and accessible.",
      price: 40,
      category: "accessories",
      gender: "unisex",
      trending: false,
    },
    {
      id: "47",
      name: "Nike Brasilia JDI",
      img: img47,
      desc: "Sleek, modern and made from durable polyester, the Nike Elemental Backpack is a storage staple. Its large zippered compartment comfortably fits shoes or gym clothes along with your books and laptop for school. Two exterior pockets help keep your small essentials organized and accessible.",
      price: 49,
      category: "accessories",
      gender: "unisex",
      trending: false,
    },
    {
      id: "48",
      name: "Nike Sportswear Essentials",
      img: img48,
      desc: "Sleek, modern and made from durable polyester, the Nike Elemental Backpack is a storage staple. Its large zippered compartment comfortably fits shoes or gym clothes along with your books and laptop for school. Two exterior pockets help keep your small essentials organized and accessible.",
      price: 29,
      category: "accessories",
      gender: "unisex",
      trending: false,
    },
  ],
  filteredProducts: [],
  bagItems: [],
  favoriteItems: [],
};

const productsSlice = createSlice({
  name: "products",
  initialState,
  reducers: {
    filterProducts: (state, action) => {
      const { gender, category } = action.payload;
      const newFilteredList = state.allProducts.filter(
        (product) => product.gender === gender && product.category === category
      );
      state.filteredProducts = newFilteredList;
    },
    addToBag: (state, action) => {
      const item = state.bagItems.find((item) => item.id === action.payload);
      if (item) {
        item.amount++;
      } else {
        state.bagItems.push({ id: action.payload, amount: 1 });
      }
    },
    increament: (state, action) => {
      const item = state.bagItems.find((item) => item.id === action.payload);
      item.amount++;
    },
    decreament: (state, action) => {
      const item = state.bagItems.find((item) => item.id === action.payload);
      if (item.amount === 1) {
        item.amount = 1;
      } else {
        item.amount--;
      }
    },
    removeFromBag: (state, action) => {
      const newBag = state.bagItems.filter(
        (item) => item.id !== action.payload
      );
      state.bagItems = newBag;
    },
    addToFav: (state, action) => {
      const favoriteItem = state.favoriteItems.find(
        (item) => item.id === action.payload
      );
      if (favoriteItem) {
        return;
      } else {
        state.favoriteItems.push({ id: action.payload, amount: 1 });
      }
    },
    removeFromFav: (state, action) => {
      const newList = state.favoriteItems.filter(
        (item) => item.id !== action.payload
      );

      state.favoriteItems = newList;
    },
  },
});

export const {
  filterProducts,
  addToBag,
  increament,
  decreament,
  removeFromBag,
  addToFav,
  removeFromFav,
} = productsSlice.actions;
export default productsSlice.reducer;
